description: test
# method: ppo

# eval: false


### env
# render: false

# max_episodes: 50000
# max_timesteps: 300

# dim_state: None
# dim_action: 4

### optim.Adam
# lr: 0.0001
# betas: (0.9, 0.999)

### rl
# gamma: 0.99

### PPO
# K_epochs: 40
# epsilon_clip: 0.2
# weight_value: 1.0
# weight_entropy: 0.005

