description: 8-agents---change-param
### env
num_vehicles: 8

### learn
load_model: false

### reward
reward_collision: -10.0
reward_timeout: -3.0
reward_done: 10.0

### train
dim_state: 10
dim_action: 3
capacity: 1000000  ## replay buffer size
batch_size: 256

n_episode: 5000
# max_steps: 1000
eval_times: 100

gamma: 0.99  # discount
tau: 0.005  # for target network update

#### epsilon-greedy
epsilon_prob_start: 1.0
epsilon_prob_end: 0.2
decay_rate: 0.99997
